name: php-todo
services:
  web-server:
    image: nginx:1.25.2
    container_name: php-nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    image: php:fpm-alpine3.18 #PHP 8.2.10
    container_name: php-fpm
    volumes:
      - ./src:/var/www/html
